version: '3.8'
services:
  db:
    image: percona/percona-server:8.0
    container_name: ps8-dsw-ys
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT:-3307}:3306"   
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
