GET http://localhost:3000/api/talleres

# @name createTaller

GET http://localhost:3000/api/talleres/{{id}}

POST http://localhost:3000/api/talleres
Content-Type: application/json

{
  "name": "invertidas",
  "datetime": "jueves 24 a las 18:00",
  "price": 8000,
  "description": "taller de invertidas para todas",
  "cupo": 20,
  "room": {1}
}

@id = {{createTaller.response.body.data.id}}

PUT http://localhost:3000/api/talleres/{{id}}
Content-Type: application/json

{
  "name": "meditacion",
  "datetime": "lunes 15 4 de la tarde",
  "price": 10000,
  "description": "meditacion para principiantes",
  "cupo": 25
}

# @name createtallerToDelete

@idToDelete = {{createtallerToDelete.response.body.data.id}}

DELETE http://localhost:3000/api/talleres/{{idToDelete}}