

GET http://localhost:3000/api/days
###
 http://localhost:3000/api/classes/professor/classes
###

POST http://localhost:3000/api/classs
Content-Type: application/json

{
    "name": "Clase de Yoga Avanzado",
    "description": "Una clase para estudiantes avanzados que buscan profundizar en su práctica de yoga.",
    "professorId": 1
    }