### (Prueba 1) Verificar que el servidor responde
GET http://localhost:3000/api/classes


### (Prueba 2) Crear la clase para el profesor Zarah
POST http://localhost:3000/api/classes
Content-Type: application/json

{
  "classData": {
    "name": "Yoga Restaurativo",
    "description": "Una clase suave para relajar el cuerpo y la mente.",
    "capacityLimit": 15,
    "day": 1, 
    "time": 2, 
    "room": 3, 
    "professor": 3
  }
}